@startuml

class InventoryManagementApplication {
    -window: Stage

    +start(Stage stage)
    +main(String[] args)
    +goToHomePage()
}

class Item {
    -name: SimpleStringProperty
    -serialNumber: SimpleStringProperty
    -value: SimpleStringProperty

    +Item()
    +Item(name, serialNumber, value)

    +clone(): Item
    +restore(Item i): void

    +setCompareTo(int sortFlag)
    +compareTo(Item i)

    +setItemBasic()
    +getItemBasic()

    +getValueString(): String
    +getValueStringProperty(): SimpleStringProperty
    +getSerialNumberString(): String
    +getSerialNumberStringProperty(): SimpleStringProperty
    +getNameString(): String
    +getNameStringProperty(): SimpleStringProperty
}

class ControllerHomePage {
    -itemList: ObservableList<Item>
    -filteredList: FilteredList<Item>
    -tableView: TableView
    -tableName: TableColumn<Item, String>
    -tableSerialNumber: TableColumn<Item, String>
    -tableValue: TableColumn<Item, String>

    +handleClear()
    +handleAdd()
    +handleRemove()
    +handleEdit()
    +handleSave()
    +handleLoad()
    +handleHelp()
    +clearList()
    +initializeList()
    +initialize()
    +handleSearchByName()
    +handleSearchBySerialNumber()
    +handleSortByName()
    +handleSortBySerialNumber()
    +handleSortByValue()
}

class ControllerEdit {
    -isValid: boolean
    -nameField: TextField
    -SerialNumberField: TextField
    -valueField: TextField
    -submitButton: Button

    +handleSubmit(): void
    +setItem(Item i): void
    +getIsValid(): boolean
}

class ControllerLoad {
    -itemList: ObservableList<Item>
    -file: File
    -fileTextBox: TextField

    +pickFile()
    +loadFile()
    +getDataWithFileType()
    +loadCSV()
    +addLineCSV()
    +loadHTML()
    +loadJSON()
    +setItemList()
}

class ControllerSave {
    -itemList: ObservableList<Item>
    -file: File
    -fileTextBox: TextField

    +pickFile()
    +saveFile()
    +setItemList()
    +saveCSV()
    +saveHTML()
    +saveJSON()
    +clearText()
}

class ControllerError {
    -errorText: Label

    +setErrorMessage(int flag)
    +showNameError()
    +showSerialNumberError()
    +showValueError()
}

class ItemArrayList {
    -itemBasicArrayList: ArrayList<ItemBasic>

    +ItemArrayList(List<Item> items)
    +add(ItemBasic itemBasic)
    +get(int i) ItemBasic
    +size()
}

class ItemBasic {
    -name: String
    -serialNumber: String
    -value: String

    +ItemBasic()
    +getName(): String
    +setName(String name)
    +getSerialNumber(): String
    +setSerialNumber(String serialNumber)
    +getValue()
    +setValue(String value)
}


InventoryManagementApplication -> ControllerHomePage

ControllerHomePage -> ControllerLoad
ControllerHomePage -> ControllerEdit
ControllerHomePage -> ControllerSave
ControllerEdit -> ControllerError

ControllerHomePage -> Item
ControllerEdit -> Item
ControllerSave -> Item
ControllerLoad -> Item
Item -> ItemArrayList
Item -> ItemBasic
ItemArrayList -> ItemBasic


@enduml